name: ci/cd pipeline

on:
  push:
    branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                go-version: 1.21
        
            - name: Run tests
              run: |
                go test -v ./...

    build-and-push-docker:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkOut@v2

            - name: Create .env file
              run: |
                echo "${{secrets.ENV}}" >> .env         

            - name: Build Docker image
              run: docker build -t haikalkamily28/mini-project:1.0.1 .
            
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_USER}}
                password: ${{secrets.DOCKER_TOKEN}}
